<?php

return array (
  'AF-BDS' => __('Badakhshan', 'enhanced-region-data'),
  'AF-BGL' => __('Baghlan', 'enhanced-region-data'),
  'AF-BAL' => __('Balkh', 'enhanced-region-data'),
  'AF-BAM' => __('Bamyan', 'enhanced-region-data'),
  'AF-DAY' => __('Daykundi', 'enhanced-region-data'),
  'AF-FRA' => __('Farah', 'enhanced-region-data'),
  'AF-FYB' => __('Faryab', 'enhanced-region-data'),
  'AF-GHA' => __('Ghazni', 'enhanced-region-data'),
  'AF-GHO' => __('Ghor', 'enhanced-region-data'),
  'AF-HEL' => __('Helmand', 'enhanced-region-data'),
  'AF-HER' => __('Herat', 'enhanced-region-data'),
  'AF-JOW' => __('Jowzjan', 'enhanced-region-data'),
  'AF-KAB' => __('Kabul', 'enhanced-region-data'),
  'AF-KAN' => __('Kandahar', 'enhanced-region-data'),
  'AF-KAP' => __('Kapisa', 'enhanced-region-data'),
  'AF-KHO' => __('Khost', 'enhanced-region-data'),
  'AF-KNR' => __('Kunar', 'enhanced-region-data'),
  'AF-KDZ' => __('Kunduz', 'enhanced-region-data'),
  'AF-LAG' => __('Laghman', 'enhanced-region-data'),
  'AF-LOG' => __('Logar', 'enhanced-region-data'),
  'AF-NAN' => __('Nangarhar', 'enhanced-region-data'),
  'AF-NIM' => __('Nimroz', 'enhanced-region-data'),
  'AF-NUR' => __('Nuristan', 'enhanced-region-data'),
  'AF-PKA' => __('Paktia', 'enhanced-region-data'),
  'AF-PKT' => __('Paktika', 'enhanced-region-data'),
  'AF-PAN' => __('Panjshir', 'enhanced-region-data'),
  'AF-PAR' => __('Parwan', 'enhanced-region-data'),
  'AF-SAM' => __('Samangan', 'enhanced-region-data'),
  'AF-SAR' => __('Sar-e Pol', 'enhanced-region-data'),
  'AF-TAK' => __('Takhar', 'enhanced-region-data'),
  'AF-URU' => __('Urozgan', 'enhanced-region-data'),
  'AF-WAR' => __('Wardak', 'enhanced-region-data'),
  'AF-ZAB' => __('Zabul', 'enhanced-region-data'),
);
