<?php

return array (
  'CD-KN' => __('Kinshasa', 'enhanced-region-data'),
  'CD-BC' => __('Kongo Central', 'enhanced-region-data'),
  'CD-KG' => __('Kwango', 'enhanced-region-data'),
  'CD-KW' => __('Kwilu', 'enhanced-region-data'),
  'CD-MA' => __('Mai-Ndombe', 'enhanced-region-data'),
  'CD-EQ' => __('Équateur', 'enhanced-region-data'),
  'CD-MO' => __('Mongala', 'enhanced-region-data'),
  'CD-NU' => __('Nord-Ubangi', 'enhanced-region-data'),
  'CD-SU' => __('Sud-Ubangi', 'enhanced-region-data'),
  'CD-TU' => __('Tshuapa', 'enhanced-region-data'),
  'CD-IT' => __('Ituri', 'enhanced-region-data'),
  'CD-HU' => __('Haut-Uele', 'enhanced-region-data'),
  'CD-BA' => __('Bas-Uele', 'enhanced-region-data'),
  'CD-TO' => __('Tshopo', 'enhanced-region-data'),
  'CD-NK' => __('Nord-Kivu', 'enhanced-region-data'),
  'CD-SK' => __('Sud-Kivu', 'enhanced-region-data'),
  'CD-MN' => __('Maniema', 'enhanced-region-data'),
  'CD-HL' => __('Haut-Lomami', 'enhanced-region-data'),
  'CD-LU' => __('Lualaba', 'enhanced-region-data'),
  'CD-HK' => __('Haut-Katanga', 'enhanced-region-data'),
  'CD-TA' => __('Tanganyika', 'enhanced-region-data'),
  'CD-LO' => __('Lomami', 'enhanced-region-data'),
  'CD-SA' => __('Sankuru', 'enhanced-region-data'),
  'CD-KC' => __('Kasaï-Central', 'enhanced-region-data'),
  'CD-KS' => __('Kasaï', 'enhanced-region-data'),
  'CD-KO' => __('Kasaï-Oriental', 'enhanced-region-data'),
);
