<?php

return array (
  'GB-ENG' => __('England', 'enhanced-regions'),
  'GB-SCT' => __('Scotland', 'enhanced-regions'),
  'GB-WLS' => __('Wales', 'enhanced-regions'),
  'GB-NIR' => __('Northern Ireland', 'enhanced-regions'),
  'GB-BDS' => __('Bedfordshire', 'enhanced-regions'),
  'GB-BKM' => __('Buckinghamshire', 'enhanced-regions'),
  'GB-CAM' => __('Cambridgeshire', 'enhanced-regions'),
  'GB-CHS' => __('Cheshire', 'enhanced-regions'),
  'GB-CON' => __('Cornwall', 'enhanced-regions'),
  'GB-CMA' => __('Cumbria', 'enhanced-regions'),
  'GB-DBY' => __('Derbyshire', 'enhanced-regions'),
  'GB-DEV' => __('Devon', 'enhanced-regions'),
  'GB-DOR' => __('Dorset', 'enhanced-regions'),
  'GB-DUR' => __('Durham', 'enhanced-regions'),
  'GB-ESX' => __('Essex', 'enhanced-regions'),
  'GB-GLS' => __('Gloucestershire', 'enhanced-regions'),
  'GB-HAM' => __('Hampshire', 'enhanced-regions'),
  'GB-HRT' => __('Hertfordshire', 'enhanced-regions'),
  'GB-KEN' => __('Kent', 'enhanced-regions'),
  'GB-LAN' => __('Lancashire', 'enhanced-regions'),
  'GB-LEI' => __('Leicestershire', 'enhanced-regions'),
  'GB-LIN' => __('Lincolnshire', 'enhanced-regions'),
  'GB-NFK' => __('Norfolk', 'enhanced-regions'),
  'GB-NYK' => __('North Yorkshire', 'enhanced-regions'),
  'GB-NTH' => __('Northamptonshire', 'enhanced-regions'),
  'GB-NTT' => __('Nottinghamshire', 'enhanced-regions'),
  'GB-OXF' => __('Oxfordshire', 'enhanced-regions'),
  'GB-SOM' => __('Somerset', 'enhanced-regions'),
  'GB-STS' => __('Staffordshire', 'enhanced-regions'),
  'GB-SFK' => __('Suffolk', 'enhanced-regions'),
  'GB-SRY' => __('Surrey', 'enhanced-regions'),
  'GB-WAR' => __('Warwickshire', 'enhanced-regions'),
  'GB-WSX' => __('West Sussex', 'enhanced-regions'),
  'GB-WOR' => __('Worcestershire', 'enhanced-regions'),
);
