<?php

return array (
  'KH-12' => __('Phnom Penh', 'enhanced-regions'),
  'KH-01' => __('Banteay Meanchey', 'enhanced-regions'),
  'KH-02' => __('Battambang', 'enhanced-regions'),
  'KH-03' => __('Kampong Cham', 'enhanced-regions'),
  'KH-04' => __('Kampong Chhnang', 'enhanced-regions'),
  'KH-05' => __('Kampong Speu', 'enhanced-regions'),
  'KH-06' => __('Kampong Thom', 'enhanced-regions'),
  'KH-07' => __('Kampot', 'enhanced-regions'),
  'KH-08' => __('Kandal', 'enhanced-regions'),
  'KH-09' => __('Koh Kong', 'enhanced-regions'),
  'KH-10' => __('Kratie', 'enhanced-regions'),
  'KH-11' => __('Mondulkiri', 'enhanced-regions'),
  'KH-22' => __('Oddar Meanchey', 'enhanced-regions'),
  'KH-13' => __('Preah Vihear', 'enhanced-regions'),
  'KH-14' => __('Prey Veng', 'enhanced-regions'),
  'KH-15' => __('Pursat', 'enhanced-regions'),
  'KH-16' => __('Ratanakiri', 'enhanced-regions'),
  'KH-17' => __('Siem Reap', 'enhanced-regions'),
  'KH-18' => __('Sihanoukville', 'enhanced-regions'),
  'KH-19' => __('Stung Treng', 'enhanced-regions'),
  'KH-20' => __('Svay Rieng', 'enhanced-regions'),
  'KH-21' => __('Takeo', 'enhanced-regions'),
  'KH-23' => __('Kep', 'enhanced-regions'),
  'KH-24' => __('Pailin', 'enhanced-regions'),
  'KH-25' => __('Tboung Khmum', 'enhanced-regions'),
);
