<?php

return array (
  'LV-001' => __('Aglonas novads', 'enhanced-regions'),
  'LV-002' => __('Aizkraukles novads', 'enhanced-regions'),
  'LV-003' => __('Aizputes novads', 'enhanced-regions'),
  'LV-004' => __('Aknīstes novads', 'enhanced-regions'),
  'LV-005' => __('Alojas novads', 'enhanced-regions'),
  'LV-006' => __('Alsungas novads', 'enhanced-regions'),
  'LV-007' => __('Alūksnes novads', 'enhanced-regions'),
  'LV-008' => __('Amatas novads', 'enhanced-regions'),
  'LV-009' => __('Apes novads', 'enhanced-regions'),
  'LV-010' => __('Auces novads', 'enhanced-regions'),
  'LV-011' => __('Ādažu novads', 'enhanced-regions'),
  'LV-012' => __('Babītes novads', 'enhanced-regions'),
  'LV-013' => __('Baldones novads', 'enhanced-regions'),
  'LV-014' => __('Baltinavas novads', 'enhanced-regions'),
  'LV-015' => __('Balvu novads', 'enhanced-regions'),
  'LV-016' => __('Bauskas novads', 'enhanced-regions'),
  'LV-017' => __('Beverīnas novads', 'enhanced-regions'),
  'LV-018' => __('Brocēnu novads', 'enhanced-regions'),
  'LV-019' => __('Burtnieku novads', 'enhanced-regions'),
  'LV-020' => __('Carnikavas novads', 'enhanced-regions'),
  'LV-021' => __('Cēsu novads', 'enhanced-regions'),
  'LV-022' => __('Cesvaines novads', 'enhanced-regions'),
  'LV-023' => __('Ciblas novads', 'enhanced-regions'),
  'LV-024' => __('Dagdas novads', 'enhanced-regions'),
  'LV-025' => __('Daugavpils novads', 'enhanced-regions'),
  'LV-026' => __('Dobeles novads', 'enhanced-regions'),
  'LV-027' => __('Dundagas novads', 'enhanced-regions'),
  'LV-028' => __('Durbes novads', 'enhanced-regions'),
  'LV-029' => __('Engures novads', 'enhanced-regions'),
  'LV-030' => __('Ērgļu novads', 'enhanced-regions'),
  'LV-RIX' => __('Rīga', 'enhanced-regions'),
  'LV-DGP' => __('Daugavpils', 'enhanced-regions'),
  'LV-JEL' => __('Jelgava', 'enhanced-regions'),
  'LV-JUR' => __('Jūrmala', 'enhanced-regions'),
  'LV-LPX' => __('Liepāja', 'enhanced-regions'),
  'LV-REZ' => __('Rēzekne', 'enhanced-regions'),
  'LV-VEN' => __('Ventspils', 'enhanced-regions'),
);
