<?php

return array (
  'MW-LI' => __('Lilongwe', 'enhanced-region-data'),
  'MW-BA' => __('Balaka', 'enhanced-region-data'),
  'MW-BL' => __('Blantyre', 'enhanced-region-data'),
  'MW-CK' => __('Chikwawa', 'enhanced-region-data'),
  'MW-CR' => __('Chiradzulu', 'enhanced-region-data'),
  'MW-CT' => __('Chitipa', 'enhanced-region-data'),
  'MW-DE' => __('Dedza', 'enhanced-region-data'),
  'MW-DO' => __('Dowa', 'enhanced-region-data'),
  'MW-KA' => __('Karonga', 'enhanced-region-data'),
  'MW-KS' => __('Kasungu', 'enhanced-region-data'),
  'MW-LK' => __('Likoma', 'enhanced-region-data'),
  'MW-MC' => __('Mchinji', 'enhanced-region-data'),
  'MW-MG' => __('Mangochi', 'enhanced-region-data'),
  'MW-MH' => __('Machinga', 'enhanced-region-data'),
  'MW-MU' => __('Mulanje', 'enhanced-region-data'),
  'MW-MW' => __('Mwanza', 'enhanced-region-data'),
  'MW-MZ' => __('Mzimba', 'enhanced-region-data'),
  'MW-NE' => __('Neno', 'enhanced-region-data'),
  'MW-NB' => __('Nkhata Bay', 'enhanced-region-data'),
  'MW-NK' => __('Nkhotakota', 'enhanced-region-data'),
  'MW-NS' => __('Nsanje', 'enhanced-region-data'),
  'MW-NU' => __('Ntcheu', 'enhanced-region-data'),
  'MW-NI' => __('Ntchisi', 'enhanced-region-data'),
  'MW-PH' => __('Phalombe', 'enhanced-region-data'),
  'MW-RU' => __('Rumphi', 'enhanced-region-data'),
  'MW-SA' => __('Salima', 'enhanced-region-data'),
  'MW-TH' => __('Thyolo', 'enhanced-region-data'),
  'MW-ZO' => __('Zomba', 'enhanced-region-data'),
);
