<?php

return array (
  'SC-01' => __('Anse aux Pins', 'enhanced-region-data'),
  'SC-02' => __('Anse Boileau', 'enhanced-region-data'),
  'SC-03' => __('Anse Etoile', 'enhanced-region-data'),
  'SC-04' => __('Au Cap', 'enhanced-region-data'),
  'SC-05' => __('Anse Royale', 'enhanced-region-data'),
  'SC-06' => __('Baie Lazare', 'enhanced-region-data'),
  'SC-07' => __('Baie Sainte Anne', 'enhanced-region-data'),
  'SC-08' => __('Beau Vallon', 'enhanced-region-data'),
  'SC-09' => __('Bel Air', 'enhanced-region-data'),
  'SC-10' => __('Bel Ombre', 'enhanced-region-data'),
  'SC-11' => __('Cascade', 'enhanced-region-data'),
  'SC-12' => __('Glacis', 'enhanced-region-data'),
  'SC-13' => __('Grand\'Anse (Mahé)', 'enhanced-region-data'),
  'SC-14' => __('Grand\'Anse (Praslin)', 'enhanced-region-data'),
  'SC-15' => __('La Digue', 'enhanced-region-data'),
  'SC-16' => __('La Rivière Anglaise', 'enhanced-region-data'),
  'SC-17' => __('Mont Buxton', 'enhanced-region-data'),
  'SC-18' => __('Mont Fleuri', 'enhanced-region-data'),
  'SC-19' => __('Plaisance', 'enhanced-region-data'),
  'SC-20' => __('Pointe La Rue', 'enhanced-region-data'),
  'SC-21' => __('Port Glaud', 'enhanced-region-data'),
  'SC-22' => __('Saint Louis', 'enhanced-region-data'),
  'SC-23' => __('Takamaka', 'enhanced-region-data'),
  'SC-24' => __('Les Mamelles', 'enhanced-region-data'),
  'SC-25' => __('Roche Caiman', 'enhanced-region-data'),
);
