<?php

return array (
  'VN-01' => __('Hanoi', 'enhanced-regions'),
  'VN-79' => __('Ho Chi Minh City', 'enhanced-regions'),
  'VN-48' => __('Da Nang', 'enhanced-regions'),
  'VN-31' => __('Hai Phong', 'enhanced-regions'),
  'VN-92' => __('Can Tho', 'enhanced-regions'),
  'VN-40' => __('Nghe An', 'enhanced-regions'),
  'VN-44' => __('Quang Binh', 'enhanced-regions'),
  'VN-45' => __('Quang Tri', 'enhanced-regions'),
  'VN-46' => __('Thua Thien Hue', 'enhanced-regions'),
  'VN-49' => __('Quang Nam', 'enhanced-regions'),
  'VN-51' => __('Quang Ngai', 'enhanced-regions'),
  'VN-52' => __('Binh Dinh', 'enhanced-regions'),
  'VN-54' => __('Phu Yen', 'enhanced-regions'),
  'VN-56' => __('Khanh Hoa', 'enhanced-regions'),
  'VN-58' => __('Ninh Thuan', 'enhanced-regions'),
  'VN-60' => __('Binh Thuan', 'enhanced-regions'),
  'VN-62' => __('Kon Tum', 'enhanced-regions'),
  'VN-64' => __('Gia Lai', 'enhanced-regions'),
  'VN-66' => __('Dak Lak', 'enhanced-regions'),
  'VN-67' => __('Dak Nong', 'enhanced-regions'),
  'VN-68' => __('Lam Dong', 'enhanced-regions'),
  'VN-70' => __('Binh Phuoc', 'enhanced-regions'),
  'VN-72' => __('Tay Ninh', 'enhanced-regions'),
  'VN-74' => __('Binh Duong', 'enhanced-regions'),
  'VN-75' => __('Dong Nai', 'enhanced-regions'),
  'VN-77' => __('Ba Ria - Vung Tau', 'enhanced-regions'),
  'VN-80' => __('Long An', 'enhanced-regions'),
  'VN-82' => __('Tien Giang', 'enhanced-regions'),
  'VN-83' => __('Ben Tre', 'enhanced-regions'),
  'VN-84' => __('Tra Vinh', 'enhanced-regions'),
  'VN-86' => __('Vinh Long', 'enhanced-regions'),
  'VN-87' => __('Dong Thap', 'enhanced-regions'),
  'VN-89' => __('An Giang', 'enhanced-regions'),
  'VN-91' => __('Kien Giang', 'enhanced-regions'),
  'VN-93' => __('Hau Giang', 'enhanced-regions'),
  'VN-94' => __('Soc Trang', 'enhanced-regions'),
  'VN-95' => __('Bac Lieu', 'enhanced-regions'),
  'VN-96' => __('Ca Mau', 'enhanced-regions'),
);
